### ISSUE TITLE
Problem with tourists

### ISSUE THREAD

**Issue by Wolfman237** [anno-mods/New-World-Tourism#13]
I've problem to activate the tourist harbour in the new world, because it wants 4000 tourists to be activated! 
![screenshot_2023-09-07-10-18-13](https://github.com/anno-mods/New-World-Tourism/assets/96538401/e2b7bba5-0234-45c2-8f77-3e1606803560)

maybe there's a unknown problem with other mods, because it wants to build up the oil harbour?

**Comment by taubenangriff** [comment]
Fixed in 2.1
